from __future__ import annotations

TASK_PENDING = "PENDING"
TASK_RUNNING = "RUNNING"
TASK_WAITING_INPUT = "WAITING_INPUT"
TASK_SUCCEEDED = "SUCCEEDED"
TASK_FAILED = "FAILED"
TASK_CANCELED = "CANCELED"
TASK_RETRYING = "RETRYING"

TERMINAL_TASK_STATUSES = {
    TASK_SUCCEEDED,
    TASK_FAILED,
    TASK_CANCELED,
}

